version: "3.3"

services:
  app:
    build: .
    container_name: rcmltb
    command: bash start.sh
    volumes:
      - /usr/src/app/downloads:/usr/src/app/downloads:rw # optional
    ports:
      - "40:40" # qbittorrent selection webserver
      - "41:41" # local mirror files webserver
      - "4040:4040" # rclone serve index webserver
    restart: on-failure
      
      
